config/routes.rb
Rails.application.routes.draw do
  root "questions#index"

  resources :animals, except: :show
  resources :curators, except: :show
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :curator

  validates :name, :kind, :curator, :monthly_cost, presence: true
  validate :is_curator_18_years_old?, if: -> { kind == "Andorinha" }
  validate :curator_name_starts_with_a?, if: -> { kind == "Gato" }
  validate :curator_monthly_costs_higher_than_1000?, on: :create

  before_save :camelcase_names

  private
  def camelcase_names
    self.name = name.camelcase
    self.kind = kind.camelcase
  end

  def is_curator_18_years_old?
    errors.add(:curator, 'Idade inválida para esta espécie') if Date.current.year - curator.birthday.year > 18
  end

  def curator_name_starts_with_a?
    errors.add(:curator, 'Nome inválido para esta espécie') if curator.name[0] == "A"
  end

  def curator_monthly_costs_higher_than_1000?
    errors.add(:curator, 'Custo mensal já está superior a R$ 1000') if curator.animals.pluck(:monthly_cost).reduce(:+) > 1000
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curator.rb
class Curator < ApplicationRecord
  has_many :animals

  validates :name, :document, :birthday, presence: true
  before_save :camelcase_name

  private
  def camelcase_name
    self.name = name.camelcase
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end

  def new
    @animal = Animal.new
  end

  def create
    animal = Animal.new(animal_params)
    if animal.save
      respond_with animal, location: animals_path
    else
      flash[:alert] = "Não foi possível criar o animal: #{animal.errors.full_messages}"
      redirect_to new_animal_path
    end
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    animal = Animal.find(params[:id])
    animal.update(animal_params)
    respond_with animal, location: animals_path
  end

  def destroy
    animal = Animal.find(params[:id])
    animal.destroy
    respond_with animal, location: animals_path
  end

  private
  def animal_params
    params.require(:animal).permit(:name, :kind, :monthly_cost, :curator_id)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/curators_controller.rb
class CuratorsController < ApplicationController
  def index
    @curators = Curator.all
  end

  def new
    @curator = Curator.new
  end

  def create
    curator = Curator.new(curator_params)
    curator.save
    respond_with curator, location: curators_path
  end

  def edit
    @curator = Curator.find(params[:id])
  end

  def update
    curator = Curator.find(params[:id])
    curator.update(curator_params)
    respond_with curator, location: curators_path
  end

  def destroy
    curator = Curator.find(params[:id])
    curator.destroy
    respond_with curator, location: curators_path
  end

  private
  def curator_params
    params.require(:curator).permit(:name, :document, :birthday)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    dogs = Animal.where(kind: "Cachorro")
    @dogs_monthly_cost_average = dogs.pluck(:monthly_cost).instance_eval { reduce(:+) / size.to_f }
    @dogs_size = dogs.size
    @dogs_names = dogs.pluck(:name)
    curators = Curator.joins(:animals).select('curators.*, sum(animals.monthly_cost) as total_cost, sum(animals.monthly_cost) * 3 as future_cost').group("curators.id").reorder("total_cost desc")
    @reordened_curators = curators
    @three_months_costs = curators.map { |curator| {"#{curator.name}": curator.future_cost } }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.slim
.page-header
  h3 Dados do Animal

.col-md-4
  = simple_form_for @animal do |f|
    = f.input :name, label: "Nome", input_html: { style: "width: 100%" }
    = f.input :kind, label: "Tipo", input_html: { style: "width: 100%" }
    = f.input :monthly_cost, label: "Custo Mensal", input_html: { style: "width: 100%" }
    
    = f.association :curator, label: "Tutor", prompt: "Selecione", selected: @animal.curator.try(:id), input_html: { style: "width: 100%" }

    hr
    =<> submit_tag "Enviar", class: "button btn btn-primary",
                                    data: { disable_with: "Enviando" }
    =<> link_to "Cancelar", :back, class: "btn btn-default"
  
  

app/views/animals/index.html.slim
.page-header
  h3 Animais

= link_to "Adicionar Animal", new_animal_path, class: "btn btn-success"

.col-md-12
  .table-responsive
    table.table.table-striped
      thead
        tr
          th Nome
          th Tipo
          th Custo Mensal
          th Tutor
          th
      tbody
        - @animals.each do |animal|
          tr
            td = animal.name
            td = animal.kind
            td = "R$ #{"%.2f" % animal.monthly_cost}"
            td = animal.curator.name
            td
              =<> link_to "editar", edit_animal_path(animal.id), class: "btn btn-sm btn-default"
              =<> link_to "excluir", animal_path(animal.id), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "Tem certeza?" }

app/views/curators/_form.html.slim
.page-header
  h3 Dados do Tutor

.col-md-4
  = simple_form_for @curator do |f|
    = f.input :name, label: "Nome", input_html: { style: "width: 100%" }
    = f.input :document, label: "Documento", input_html: { style: "width: 100%" }
    = f.input :birthday, label: "Data de Nascimento", input_html: { style: "width: 100%" }
    
    hr
    =<> submit_tag "Enviar", class: "button btn btn-primary",
                                    data: { disable_with: "Enviando" }
    =<> link_to "Cancelar", :back, class: "btn btn-default"
  
  

app/views/curators/edit.html.slim
= render "form"

app/views/curators/index.html.slim
.page-header
  h3 Tutores

= link_to "Adicionar Tutor", new_curator_path, class: "btn btn-success"

.col-md-12
  .table-responsive
    table.table.table-striped
      thead
        tr
          th Nome
          th Documento
          th Data de Nascimento
          th
      tbody
        - @curators.each do |curator|
          tr
            td = curator.name
            td = curator.document
            td = curator.birthday.strftime("%d/%m/%Y")
            td
              =<> link_to "editar", edit_curator_path(curator.id), class: "btn btn-sm btn-default"
              =<> link_to "excluir", curator_path(curator.id), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "Tem certeza?" }

app/views/curators/new.html.slim
= render "form"

app/views/layouts/application.html.slim
html
  head
    title Petlove Backend
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  body
    header
      .navbar.navbar-default
        .container-fluid
          .navbar-header
            = link_to "Home", :root, class: "navbar-brand"
          ul.nav.navbar-nav
            li = link_to "Animais", animals_path
          ul.nav.navbar-nav
            li = link_to "Tutores", curators_path
    
    .container
      .col-md-12.text-center
        - if notice.present?
          p.alert.alert-success = notice
        - elsif alert.present?
          p.alert.alert-danger = alert
      = yield

app/views/questions/index.html.slim
h2 Questões

.col-md-12
  .page-header
    h4 Qual é o custo médio dos animais do tipo cachorro?
  div style="margin: 5px 0"
    | Query: Animal.where(kind: "Cachorro").pluck(:monthly_cost).instance_eval { reduce(:+) / size.to_f }
  p = "Resposta: R$ #{"%.2f" % @dogs_monthly_cost_average}"
 
  .page-header
    h4 Quantos cachorros existem no sistema?
  div style="margin: 5px 0"
    | Query: Animal.where(kind: "Cachorro").size
  p = "Resposta: #{@dogs_size}"
  
  .page-header
    h4 Qual o nome dos donos dos cachorros (Array de nomes)
  div style="margin: 5px 0"
    | Query: Animal.where(kind: "Cachorro").pluck(:name)
  p = "Resposta: #{@dogs_names}"
  
  .page-header
    h4 Retorne as pessoas ordenando pelo custo que elas tem com os animais (Maior para menor)
  div style="margin: 5px 0"
    | Query: Curator.joins(:animals).select('curators.*, sum(animals.monthly_cost) as total_cost').group("curators.id").reorder("total_cost desc")
  p = "Resposta: #{@reordened_curators.to_a.pluck(:name)}"
  
  .page-header
    h4 Levando em consideração o custo mensal, qual será o custo de 3 meses de cada pessoa?
  div style="margin: 5px 0"
    | Query: Curator.joins(:animals).select('curators.*, sum(animals.monthly_cost) * 3 as future_cost').group("curators.id")
  p = "Resposta: #{@three_months_costs}"
  